"""empty message

Revision ID: 190ee304be93
Revises: 64dfc27cfc5a
Create Date: 2022-08-13 14:10:27.878355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '190ee304be93'
down_revision = '64dfc27cfc5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('website_link', sa.String(length=120), nullable=True))
    op.add_column('Artist', sa.Column('is_seeking_venues', sa.Boolean(), nullable=True))
    op.add_column('Artist', sa.Column('seeking_venues_desc', sa.String(length=200), nullable=True))
    op.add_column('Venue', sa.Column('website_link', sa.String(length=120), nullable=True))
    op.add_column('Venue', sa.Column('is_seeking_talent', sa.Boolean(), nullable=True))
    op.add_column('Venue', sa.Column('seeking_talent_desc', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'seeking_talent_desc')
    op.drop_column('Venue', 'is_seeking_talent')
    op.drop_column('Venue', 'website_link')
    op.drop_column('Artist', 'seeking_venues_desc')
    op.drop_column('Artist', 'is_seeking_venues')
    op.drop_column('Artist', 'website_link')
    # ### end Alembic commands ###
